    [theme]
    primaryColor = "#6d5c43"
    backgroundColor = "#f0f0f5"
    secondaryBackgroundColor = "#e0e0ef"
    textColor = "#262730"
    font = "sans serif"    
    base = "light"  # atau base = "dark"